In [5]:
#         :: 限定只能是Pointy类型
#         -> 条件函数 (匿名函数)
#         ... 展开操作符
#         => 键值对
#         <: 数组
#         函数! 表示函数修改了参数

mutable struct FooC
    a::Int32 
    b::Real 
end

w=FooC(1, 2);
typeof(w.b)
w.b = 3.2;
typeof(w.b)


InexactError: InexactError: Real(3 + 2im)

In [2]:
import Pkg
Pkg.activate(".")

Activating new environment at `C:\Users\Sword\JuliaProjects\Project.toml`


In [8]:
Union{} <: Type

true

In [4]:
# 元素类型
# typeof((1,"foo",2.5))
1,"foo",2.5
typeof(ans)


Tuple{Int64,String,Float64}

In [9]:
# 元组展开
(1, 2, (10.5,"abc",3,4,5,6,7,7)..., 3)

(1, 2, 10.5, "abc", 3, 4, 5, 6, 7, 7, 3)

In [8]:
a = (10.5,"abc",3,4,5,6,7,7,8,2)
(1, 2, a..., 3)

(1, 2, 10.5, "abc", 3, 4, 5, 6, 7, 7, 8, 2, 3)

In [13]:
b=a[end],a[1]

(2, 10.5)

In [27]:
# 键值对
Pair{A,B} <: Any
    first::A
    second::B

UndefVarError: UndefVarError: A not defined

In [39]:
Pair(1, 3.2)
typeof(ans)

a = 1=>3.2
b = 1.0=>5
print(a,"\n")
print(b,"\n")
print(a.first,"\n")
print(a[1])

1 => 3.2
1.0 => 5
1
1

In [56]:
p = Dict("A"=>1,"B"=>2)
p["A"]
p["C"] = 3
get(p, "B", 1)
get!(p,"D",5)
delete!(p,"D")
pop!(p,"C")
length(p)
p.count
print(keys(p),"\n")
print(values(p),"\n")
for k in keys(p) 
    println(k, "'s value is ", p[k])
end
print(collect(values(p)))

["B", "A"]
[2, 1]
B's value is 2
A's value is 1


2-element Array{Int64,1}:
 2
 1

In [58]:
# 集合

a = Set([1,2,3,4])
b = Set([1,3,5])
x = union(a,b)        #并集
y = intersect(a,b)    #交集
z = setdiff(a,b)      #补集，在 a中，但不在 b中
print(x,"\n",y,"\n",z)


Set([4, 2, 3, 5, 1])
Set([3, 1])
Set([4, 2])

In [63]:
false & missing


false

In [65]:
#    函数
addtwo(x, y) = x + y
addtwo(5, 10)

15

In [67]:
x=10
function change_value(y)
    y=17
end
change_value(x)
x

10

In [69]:
methods(f)

UndefVarError: UndefVarError: f not defined

In [2]:
struct FooA 
    a
    b::Float64
end

In [3]:
FooA(a, b::Float64) 
FooA(a, b)

UndefVarError: UndefVarError: b not defined

In [4]:
FooA(x::Float64) = FooA(x, x)

FooA

In [5]:
FooA(1.0)

FooA(1.0, 1.0)

In [6]:
FooA(x::T) where T<:Integer = FooA(2x, 3x+10.8)

FooA

In [7]:
FooA(1)

FooA(2, 13.8)

In [11]:
methods(FooA)

# 6 methods for generic function "(::Type)":
[1] FooA() in Main at In[9]:1
[2] FooA(x::Float64) in Main at In[4]:1
[3] FooA(x::T) where T<:Integer in Main at In[6]:1
[4] FooA(m) in Main at In[9]:1
[5] FooA(a, b::Float64) in Main at In[2]:2
[6] FooA(m, n) in Main at In[9]:1

In [9]:
FooA(m=1.0, n=2.0) = FooA(m, n)

FooA

In [10]:
FooA()

FooA(1.0, 2.0)

In [12]:
# 数组
A = Array{Float64, 2}(undef, 2, 3)

2×3 Array{Float64,2}:
 0.0           1.31038e-315  4.94066e-324
 4.94066e-324  4.94066e-324  1.31038e-315

In [17]:
print(Matrix,"\n")
Vector

Array{T,2} where T


Array{T,1} where T

In [33]:
[1.1,2,3,4,(1,2,3,4)...,6]

9-element Array{Float64,1}:
 1.1
 2.0
 3.0
 4.0
 1.0
 2.0
 3.0
 4.0
 6.0

In [45]:
[1.1 2 3 ;1 2 4;1 4 6]

3×3 Array{Float64,2}:
 1.1  2.0  3.0
 1.0  2.0  4.0
 1.0  4.0  6.0

In [46]:
hcat(1, 2, 3, 4)

1×4 Array{Int64,2}:
 1  2  3  4

In [47]:
vcat(1, 2, 3, 4)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [53]:
hvcat(3, 1, 2, 3, 4, 5, 6)

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [63]:
A1 = zeros(Int64, 4,5)
A2 = zeros(Float64, (2,3))
B1 = ones(Rational, 2,3)
B2 = trues((2,3))
C1 = rand(Float64,2,3)
# C2 = Array(UniformScaling{Float32}(1), 2, 3)
print(A1,"\n")
print(A2,"\n")
print(B1,"\n")
print(B2,"\n")
print(C1,"\n")
# print(C2,"\n")


[0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0]
[0.0 0.0 0.0; 0.0 0.0 0.0]
Rational[1//1 1//1 1//1; 1//1 1//1 1//1]
Bool[1 1 1; 1 1 1]
[0.9497922573139952 0.39985710431393673 0.3239253566525422; 0.29956562280264043 0.3821455071569857 0.205685132343836]


In [ ]:
A1 = zeros(Int64, 4,5)

In [70]:
A=range(1, stop=6)
foreach(print, A)

123456

In [72]:
dump(1:3)   #dump查看内部结构

UnitRange{Int64}
  start: Int64 1
  stop: Int64 3


In [81]:
V = rand(4)
[ 0.25*V[i-1] + 0.5*V[i] + 0.25*V[i+1] for i=2:length(V)-1 ]


2-element Array{Float64,1}:
 0.21389745622402329
 0.5329799123590335 

In [93]:
[i*j for i=1:9 for j=i:9 if i+j==12]

4-element Array{Int64,1}:
 27
 32
 35
 36

In [96]:
@time [i^2+2j-1.3z for i=1:2,j∈2:5, z in 1:3]

  0.052617 seconds (127.25 k allocations: 5.860 MiB)


2×4×3 Array{Float64,3}:
[:, :, 1] =
 3.7  5.7   7.7   9.7
 6.7  8.7  10.7  12.7

[:, :, 2] =
 2.4  4.4  6.4   8.4
 5.4  7.4  9.4  11.4

[:, :, 3] =
 1.1  3.1  5.1   7.1
 4.1  6.1  8.1  10.1

In [94]:
@time sum(1/n^2 for n=1:100)

  0.023966 seconds (61.11 k allocations: 3.157 MiB)


1.6349839001848923

In [106]:
a=[1,2,3,4,5,6,7]
for i in range(1,stop=length(a)-1)
    print(a[end-i],",")
end

6,5,4,3,2,1,

In [107]:
d = rand(3,4,2,2)

3×4×2×2 Array{Float64,4}:
[:, :, 1, 1] =
 0.707031  0.927139  0.546423  0.982169
 0.275604  0.361631  0.548126  0.568048
 0.370099  0.50345   0.262378  0.887629

[:, :, 2, 1] =
 0.501684  0.065994  0.0975279  0.393849
 0.471877  0.999381  0.675675   0.196134
 0.165698  0.536776  0.0147433  0.357985

[:, :, 1, 2] =
 0.103467  0.681294  0.226992  0.722399  
 0.710186  0.902976  0.28594   0.659466  
 0.232468  0.926562  0.493048  0.00733013

[:, :, 2, 2] =
 0.584286  0.335218   0.231128  0.581232
 0.910883  0.33525    0.123369  0.196762
 0.627283  0.0512738  0.262244  0.314743

In [112]:
print(d[1, 1, 1, 2],"\n")
i = CartesianIndex(1, 1, 1, 2)
d[i]                               #访问高纬数组

0.10346652228802444


0.10346652228802444